version: '3.9'
services:
  db:
    image: mariadb:10.6
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: isucari
      MYSQL_PASSWORD: isucari
      MYSQL_DATABASE: isucari

volumes:
  db-data:
